#!/bin/bash
# Pre-compact context saver
# Saves critical session context before Claude Code compacts the conversation.
# The output file survives compaction and should be read at session resumption.
#
# Hook: PreCompact
# Level: L3+

set -e

CONTEXT_FILE="memory/compact-context.md"
SESSION_NOTES="memory/session-notes.md"

# Ensure memory directory exists
mkdir -p memory

# ─── Gather context from filesystem ──────────────────────────
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

# Recent git activity
RECENT_COMMITS=$(git log --oneline -10 2>/dev/null || echo "  (no git history)")

# Currently modified files
MODIFIED_FILES=$(git diff --name-only 2>/dev/null || echo "  (no changes)")
STAGED_FILES=$(git diff --cached --name-only 2>/dev/null || echo "  (no staged)")

# Untracked new files
UNTRACKED=$(git ls-files --others --exclude-standard 2>/dev/null | head -20 || echo "  (none)")

# Current branch
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")

# Session notes (if skills/commands have been appending to this file)
SESSION_CONTEXT=""
if [ -f "$SESSION_NOTES" ]; then
  SESSION_CONTEXT=$(cat "$SESSION_NOTES")
fi

# [SPEC] Add project-specific context sources here:
# Example: CURRENT_TODOS=$(grep -r 'TODO' src/ --include='*.ts' | head -10)

# ─── Write context file ─────────────────────────────────────
cat > "$CONTEXT_FILE" << EOF
# Compact Context — saved at $TIMESTAMP

> This file was auto-generated by pre-compact-save.sh before conversation compaction.
> Read this file to restore context from the previous conversation segment.

## Branch
$BRANCH

## Recent commits
\`\`\`
$RECENT_COMMITS
\`\`\`

## Modified files (unstaged)
\`\`\`
$MODIFIED_FILES
\`\`\`

## Staged files
\`\`\`
$STAGED_FILES
\`\`\`

## Untracked files
\`\`\`
$UNTRACKED
\`\`\`
EOF

# Append session notes if they exist
if [ -n "$SESSION_CONTEXT" ]; then
  cat >> "$CONTEXT_FILE" << EOF

## Session notes
$SESSION_CONTEXT
EOF
fi

cat >> "$CONTEXT_FILE" << 'EOF'

## Instructions
- Review the context above to understand what was happening before compaction
- Check git status and git log for the most current state
- Continue from where the previous conversation left off
- If session notes mention pending tasks, prioritize those
EOF

echo "Context saved to $CONTEXT_FILE"
exit 0
